version: '3.4'

services:
  scholarbeestudentsfe:
    image: scholarbeestudentsfe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3020:3020
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
