version: '3.4'

services:
  scholarbeestudentsfe:
    image: scholarbeestudentsfe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3020:3020
